### ISSUE TITLE
How protect server ip form getting banned by opera 

### ISSUE THREAD

**Issue by beshoo** [Snawoot/opera-proxy#14]
Dear support.
I want to connect to opera proxy via TOR proxy, I have rotated tor proxy.
How can I connect to opera-proxy and pass my TOR proxy to it?
`export http_proxy=[tor_proxy] ./opera-proxy
`does not work.

Reards

**Comment by Snawoot** [comment]
Hi!

Assuming your tor instance accepts SOCKS5 connections on port 9050, you can run it like this:

```
opera-proxy -proxy socks5h://127.0.0.1:9050 -timeout 30s
```

Extended timeout parameter is set to 30 seconds (instead of default 10 seconds) for practical reasons because Tor can be sluggish.
