### ISSUE TITLE
I think there is a problem with country selection

### ISSUE THREAD

**Issue by beshoo** [Snawoot/opera-proxy#16]
When using this command
`opera-proxy -country AM`
to use the USA country, I got this IP address on ip2location.com
2001:67c:2628:647:12::162 which is in Sweden [SE].

But when I use Opera browser and set the VPN to America 
I got this IP address on ip2location.com
2001:67c:2628:647:12::3e
which is in USA

**Comment by Snawoot** [comment]
2001:67c:2628:647:12::162 and 2001:67c:2628:647:12::3e are in same subnet, it's unlikely they're in different countries. Looks like ip2location DB is largely imprecise.

Industry standard for that is Maxmind GeoIP services, which shows US for both addresses: https://www.maxmind.com/en/geoip-demo
