### ISSUE TITLE
WebRTC Leaks ?

### ISSUE THREAD

**Issue by IceWreck** [Snawoot/opera-proxy#2]
Hey, this is great for scripts and such but when using this with browsers (both chromium and firefox) its leaking your real IP addresses.

The odd thing is I'm blocking WebRTC leaks on both browsers using uBlock Origin's prevent WebRTC leak and have disabled all other extensions and checked but its still leaking whenever the proxy is enabled which has led me to conclude that opera-proxy is at fault. (might be wrong tho)

I'm using it as an http proxy if that matters, not socks5.
Latest version, compiled from search.

**Comment by Snawoot** [comment]
Hi!

opera-proxy can't contribute to WebRTC leaks because it's the browser who handles WebRTC sessions. If you are using Chrome, try other extensions or open issue at ublock origin. If you are using Firefox, set `media.peerconnection.enabled` to `false` on `about:config` page.
