### ISSUE TITLE
Connect to proxy curl C++ help...

### ISSUE THREAD

**Issue by ExerKey** [Snawoot/opera-proxy#20]
Привет, я использовал opera-proxy.windows-amd64.exe, всё работает.
Написал программу для получения логина и пароля по твоему примеру на GO.
Но я не могу подключится к прокси, посмотри код пожалуйста, уже неделю голову ломаю, не могу подключится и всё.

void test_proxy()
{
	CURL* curl;	
        CURLcode res;
	struct curl_slist* host = NULL;
	char resolve[100];

	curl = curl_easy_init();
	if (curl)
	{	
		sprintf(resolve, "eu0.sec-tunnel.com:%s:%s", find_opera_ips[0].port, find_opera_ips[0].ip);
		host = curl_slist_append(host, resolve);
		curl_easy_setopt(curl, CURLOPT_RESOLVE, host);
		curl_easy_setopt(curl, CURLOPT_URL, "https://example.com");
		curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
		curl_easy_setopt(curl, CURLOPT_USERAGENT, userAgent);
		curl_easy_setopt(curl, CURLOPT_HEADER, 1L);
		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
		curl_easy_setopt(curl, CURLOPT_PROXY, "eu0.sec-tunnel.com:443");
		curl_easy_setopt(curl, CURLOPT_PROXYUSERNAME, login);
		curl_easy_setopt(curl, CURLOPT_PROXYPASSWORD, device_password);
		curl_easy_setopt(curl, CURLOPT_PROXYTYPE, CURLPROXY_HTTP);

		res = curl_easy_perform(curl);
	}
	        curl_easy_cleanup(curl);

		if (res == CURLE_OK)
		{
			printf("Error code: %d\n", res);
			return;
		}
}

Вывод с консоли : 
* Added eu0.sec-tunnel.com:443:77.111.247.55 to DNS cache
* timeout on name lookup is not supported
* Hostname eu0.sec-tunnel.com was found in DNS cache
*   Trying 77.111.247.55:443...
* Connected to eu0.sec-tunnel.com (77.111.247.55) port 443 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to example.com:443
* Proxy auth using Basic with user 'C5AE7A2438BE4559F244A937F1C319D23E16F960'
> CONNECT example.com:443 HTTP/1.1
Host: example.com:443
Proxy-Authorization: Basic QzVBRTdBMjQzOEJFNDU1OUYyNDRBOTM3RjFDMzE5RDIzRTE2Rjk2MDpleUpoYkdjaU9pSkZRMFJJTFVWVEswRXlOVFpMVnlJc0ltTjBlU0k2SWtwWFZDSXNJbVZ1WXlJNklrRXlOVFpIUTAwaUxDSmxjR3NpT25zaWEzUjVJam9pUlVNaUxDSmpjbllpT2lKUUxUSTFOaUlzSW5naU9pSkdXVVJVTkZsRFpWUnZRVU5YTW1weFdGUm1abk4yYVZkdE1ETmxkekZDTlROMWVEQkRZMWRJWldaRklpd2llU0k2SW1sV1NUZFlkVkZ0TjNJNVUzcFFXVkYyYlVjMFYxcEdSMVp1VjFFeU5sUk5PRE5uWlZoS01uQXdRbGtpZlgwLkU5dC1EbzBDdUQ0V3dOd3VDSkFrRjUxRXk4NnNNZTN2UFNZVEEtWWZUNnNpTC1lTE9OdlJWZy45TWJIM2hEeTZxU2xkZ3M5LnJrRXUzcWNBZjI2ekp1TmdjTEJkaVZZaHp5ZHJjWlIzV2tvTy1LQ2gtWkxtZF9EWHdhMjMwMWYxVUJjY2Y2NjdLLWJ1TmEwWGdOYTVCdTI4alU5YU1jVDlmQVRGNHNXMkJRMm04bmhrNWR5cVBmbU9tUEQ1UUo4ckN5clhlcmhGRi1PdkFjUi1UQ181QUNoRE8zb1lvMlBBMmNkZmR0alFKTXJ2b2lGa2I3eVcwQ2ZHdmVuRl9lMVJkdU05Wm00aFcxOVJVM0swbVNmZnhYSVhsUHA1UGFpWWxoSzBMdER0emxWMFp5ZVNNdi00OFpEM3p3N01RUGJ5QTZMeWc0cnNHR00yQm5IQjFSUE53ejBoN00yU2VVcUxpa2xhVHI0XzBtN3pjcHlheHVYVFNIcUh0QUFtUWRsbmlJal84RTJKQ09HUVY2QlN4VG1aaklEbnZUQ0NtSlNjREFBNHJYdTJDaVFpb29pX18teWZZZVVYZXNOMGVRSnBEWm15dC1zZEFQOFBXZElXb2lMdE5EN3JiZ29mVE5jaDkzRm5FOUt2SmpubW9hc2JzT1hGa3hWaU9NS0pwd0JSN3NvcmVKWmxib1IyREZ3Lk1pUXk3aWhZVWtENmJYNmZUclctd2c=
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36 OPR/74.0.3911.232
Proxy-Connection: Keep-Alive

* Recv failure: Connection was reset
* Received HTTP code 0 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0

**Comment by Snawoot** [comment]
Привет! Попробуй CURLOPT_PROXYTYPE = CURLPROXY_HTTPS

**Comment by ExerKey** [comment]
> Привет! Попробуй CURLOPT_PROXYTYPE = CURLPROXY_HTTPS
Большое спасибо!!!
Я CURLPROXY_HTTPS ставил, но была ошибка с сертификатом.
Помогло CURLOPT_PROXY_SSL_VERIFYHOST CURLOPT_PROXY_SSL_VERIFYPEER.

**Comment by Snawoot** [comment]
> Помогло CURLOPT_PROXY_SSL_VERIFYHOST CURLOPT_PROXY_SSL_VERIFYPEER.

Такие настройки допускают MITM, так что нужно разбираться, что не так с сертом.

**Comment by sergeevabc** [comment]
Ребята, а можно ли как-то получить логин, пароль и список проксей с помощью обычного вызова Curl или даже PowerShell?

**Comment by Snawoot** [comment]
@sergeevabc 

Да. Запускаем команду:

```
opera-proxy -list-proxies
```

Получаем вывод:

```
MAIN    : 2025/07/20 18:33:56 main.go:195: INFO     opera-proxy client version v1.8.1-3-gc17f517 is starting...
MAIN    : 2025/07/20 18:33:56 main.go:438: INFO     Attempting action "anonymous registration", attempt #1...
MAIN    : 2025/07/20 18:33:56 main.go:441: INFO     Action "anonymous registration" succeeded on attempt #1
MAIN    : 2025/07/20 18:33:56 main.go:438: INFO     Attempting action "device registration", attempt #1...
MAIN    : 2025/07/20 18:33:56 main.go:441: INFO     Action "device registration" succeeded on attempt #1
MAIN    : 2025/07/20 18:33:56 main.go:438: INFO     Attempting action "discover", attempt #1...
Proxy login: 2DC8028420C1ADF64ACAFB74CA930E2921654E26
Proxy password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJNTU9ZUlBZU2lZaGtSSG53OHI5VVJRWEZpTURneFU4bVRlYkRZOGYtd1BrIiwieSI6ImZFOXZPdy04TktoZnpmelo3NmFtS0pkTGhqV1J5dlFBZlNIN1MwdzMtaE0ifX0.Nw4mbiaQxFsEGQeCt8c2sQ-o_tagHTo1jyO0IAXmKTXfkVUvwG0cDw.mjSL9_xN9s7TiNI7.RXtdikzSz1NoiAthJoAhg5S8gxoyopcjLIlLFN7OMiw4OrFZ3wWzs_cPU6aib-jiKRd5EZ1jE2D1rPvE1EwcpCgAvjqxCFcmrZz3TnAXe3CxQgZBQgLQXpgZjgcIc-pHuOlqKrT3_YeBc108pPWvXys7C3NGZzqylIyYqqk_R4TDNxDFdcx7ml9XDgUcUV3UekCWS3fyqEiKfEPRkk6_9IedUcC6zQehapRNs2ndKPpjUEm6oFI351VSBNMm6x7_xS_2ibdt8XTsdbw1Ezsvr2b1dWclMYQUzao75ZjkX_JU3MCfOHzYNL5BxZFLRXD7APvVK7oPwg9zXrieZyf6Xy3dFCjITAUy7GlU3CpGsBNL4BLjSGNfeWl_KPud2W5HIxWBWA_nLMjLYpPRmiSEaa0hYI8bPno0OtRO0NYxuxlReKhxyMOqKLrUd7NClgXoMAvufyeiVQ.9eiUweFD0-O-cK8hbgn3HA
Proxy-Authorization: Basic MkRDODAyODQyMEMxQURGNjRBQ0FGQjc0Q0E5MzBFMjkyMTY1NEUyNjpleUpoYkdjaU9pSkZRMFJJTFVWVEswRXlOVFpMVnlJc0ltTjBlU0k2SWtwWFZDSXNJbVZ1WXlJNklrRXlOVFpIUTAwaUxDSmxjR3NpT25zaWEzUjVJam9pUlVNaUxDSmpjbllpT2lKUUxUSTFOaUlzSW5naU9pSk5UVTlaVWxCWlUybFphR3RTU0c1M09ISTVWVkpSV0VacFRVUm5lRlU0YlZSbFlrUlpPR1l0ZDFCcklpd2llU0k2SW1aRk9YWlBkeTA0VGt0b1pucG1lbG8zTm1GdFMwcGtUR2hxVjFKNWRsRkJabE5JTjFNd2R6TXRhRTBpZlgwLk53NG1iaWFReEZzRUdRZUN0OGMyc1Etb190YWdIVG8xanlPMElBWG1LVFhma1ZVdndHMGNEdy5talNMOV94TjlzN1RpTkk3LlJYdGRpa3pTejFOb2lBdGhKb0FoZzVTOGd4b3lvcGNqTElsTEZON09NaXc0T3JGWjN3V3pzX2NQVTZhaWItamlLUmQ1RVoxakUyRDFyUHZFMUV3Y3BDZ0F2anF4Q0ZjbXJaejNUbkFYZTNDeFFnWkJRZ0xRWHBnWmpnY0ljLXBIdU9scUtyVDNfWWVCYzEwOHBQV3ZYeXM3QzNOR1p6cXlsSXlZcXFrX1I0VEROeERGZGN4N21sOVhEZ1VjVVYzVWVrQ1dTM2Z5cUVpS2ZFUFJrazZfOUllZFVjQzZ6UWVoYXBSTnMybmRLUHBqVUVtNm9GSTM1MVZTQk5NbTZ4N194U18yaWJkdDhYVHNkYncxRXpzdnIyYjFkV2NsTVlRVXphbzc1WmprWF9KVTNNQ2ZPSHpZTkw1QnhaRkxSWEQ3QVB2Vks3b1B3Zzl6WHJpZVp5ZjZYeTNkRkNqSVRBVXk3R2xVM0NwR3NCTkw0QkxqU0dOZmVXbF9LUHVkMlc1SEl4V0JXQV9uTE1qTFlwUFJtaVNFYWEwaFlJOGJQbm8wT3RSTzBOWXh1eGxSZUtoeHlNT3FLTHJVZDdOQ2xnWG9NQXZ1ZnllaVZRLjllaVV3ZUZEMC1PLWNLOGhiZ24zSEE=
MAIN    : 2025/07/20 18:33:56 main.go:441: INFO     Action "discover" succeeded on attempt #1

host,ip_address,port
eu0.sec-tunnel.com,77.111.244.51,443
eu1.sec-tunnel.com,77.111.244.74,443
eu2.sec-tunnel.com,77.111.244.76,443
eu3.sec-tunnel.com,77.111.244.52,443
```

Из этих данных мы можем составить команду curl:

```sh
curl --proxy https://2DC8028420C1ADF64ACAFB74CA930E2921654E26:eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJNTU9ZUlBZU2lZaGtSSG53OHI5VVJRWEZpTURneFU4bVRlYkRZOGYtd1BrIiwieSI6ImZFOXZPdy04TktoZnpmelo3NmFtS0pkTGhqV1J5dlFBZlNIN1MwdzMtaE0ifX0.Nw4mbiaQxFsEGQeCt8c2sQ-o_tagHTo1jyO0IAXmKTXfkVUvwG0cDw.mjSL9_xN9s7TiNI7.RXtdikzSz1NoiAthJoAhg5S8gxoyopcjLIlLFN7OMiw4OrFZ3wWzs_cPU6aib-jiKRd5EZ1jE2D1rPvE1EwcpCgAvjqxCFcmrZz3TnAXe3CxQgZBQgLQXpgZjgcIc-pHuOlqKrT3_YeBc108pPWvXys7C3NGZzqylIyYqqk_R4TDNxDFdcx7ml9XDgUcUV3UekCWS3fyqEiKfEPRkk6_9IedUcC6zQehapRNs2ndKPpjUEm6oFI351VSBNMm6x7_xS_2ibdt8XTsdbw1Ezsvr2b1dWclMYQUzao75ZjkX_JU3MCfOHzYNL5BxZFLRXD7APvVK7oPwg9zXrieZyf6Xy3dFCjITAUy7GlU3CpGsBNL4BLjSGNfeWl_KPud2W5HIxWBWA_nLMjLYpPRmiSEaa0hYI8bPno0OtRO0NYxuxlReKhxyMOqKLrUd7NClgXoMAvufyeiVQ.9eiUweFD0-O-cK8hbgn3HA@eu0.sec-tunnel.com:443 --resolve eu0.sec-tunnel.com:443:77.111.244.51 https://api.ipify.org
```

И такая команда выведет:

```
77.111.244.51
```
