### ISSUE TITLE
PROXY   : 2022/04/27 17:58:26 handler.go:39: ERROR    Can't satisfy CONNECT request: socks connect tcp ... : i/o timeout

### ISSUE THREAD

**Issue by TheRealSoundWave** [Snawoot/opera-proxy#22]
I'm using opera-proxy thru TOR on snap like so:

snap run opera-proxy -proxy socks5://127.0.0.1:9050 -country EU -bind-address 127.0.0.1:33333 -verbosity 30 -timeout 360s

I get theses errors:

PROXY   : 2022/04/27 17:58:26 handler.go:39: ERROR    Can't satisfy CONNECT request: socks connect tcp 127.0.0.1:9050->77.111.247.182:443: read tcp 127.0.0.1:58226->127.0.0.1:9050: i/o timeout

PROXY   : 2022/04/27 18:00:48 handler.go:78: ERROR    HTTP fetch error: EOF

I thought that the  '-timeout 360s' would solve the errors. It seems that TOR is too slow for opera-proxy.

**Comment by Snawoot** [comment]
... or opera servers don't allow access via tor to prevent abuse, who knows.

**Comment by TheRealSoundWave** [comment]
Well, that's weird, cause it's working!!! Maybe it's your dialer.DialContext that's trying to do stuff as the errors seems to be pretty much random and occurs in HandleTunnel function. Can you at least explain what the error means in regards of your coding, since there is no comments, and since the problem occurs randomly. Seems to me that's a traffic issue badly handled.
