### ISSUE TITLE
Помощь с запуском в фоне

### ISSUE THREAD

**Issue by Hlebuw3k** [Snawoot/opera-proxy#25]
Я не разобрался как запустить в фоне, что-бы окно терминала не мешало. На посте в Хабр упоминается запуск с помощью "планировщика задач" но даже с ним окно все равно видно. Как делать все эти аргументы я тоже не понял, хоть и очень интересно. Кроме этих деталей, работает идеально.

Использую opera-proxy.windows-amd64.exe, запускаю через планировщик задач при входе в систему.

**Comment by Snawoot** [comment]
Здравствуйте!

По-моему нужно там в опциях выставить, чтобы запускалось даже когда вы не вошли в систему (тогда запуск будет не в десктопном сеансе, а в фоне). Но точно не помню, поэкспериментируйте с опциями.

Либо воспользуйтесь http://nssm.cc/usage - этим инструментом можно любую консольную прогу заставить работать в фоне и автоматически собирать логи её работы.

**Comment by Hlebuw3k** [comment]
Спасибо! Нужно было поставить "Выполнять для всех пользователей" и "При запуске"
