### ISSUE TITLE
Возможность расшарить Socks Proxy

### ISSUE THREAD

**Issue by atomexpert** [Snawoot/opera-proxy#26]
Здравствуйте! Подскажите пожалуйста, есть ли возможность открывать порты через Socks прокси, а не http?

**Comment by Snawoot** [comment]
Здравствуйте! Такая возможность не реализована и не планируется. Скорее всего найдутся адаптеры, которые принимают соединения как SOCKS5-прокси и перенаправляют их в HTTP-прокси. В частности, можно взять https://github.com/Snawoot/socks5-server и сделать ему опцию, которая бы использовала [кастомный Dial](https://pkg.go.dev/github.com/armon/go-socks5#Config), который бы уже шёл в HTTP-прокси. Наверняка что-то и уже готовое имеется.

**Comment by atomexpert** [comment]
Понял, спасибо!

**Comment by Snawoot** [comment]
@przemyslaw0 hi!

Can you please give me a link to DNSCrypt implementation you're referring to? I believe there is a good reason for that: SOCKS5 can forward UDP traffic while HTTP proxies can't, these forward only TCP connections. opera-proxy uses some upstream HTTPS proxies which can't forward UDP too. Therefore even if I'll implement incomplete SOCKS5 support for opera-proxy, it will not be enough for DNSCrypt which is operating on UDP datagrams, not TCP connections.

**Comment by Snawoot** [comment]
@przemyslaw0 thanks!

**Comment by alpominth** [comment]
I had a better idea: serving SOCKS5 and HTTP on same port (it's already implemented in Glider): https://github.com/nadoo/glider/blob/master/proxy/mixed/mixed.go

I don't know how to code in Go, but looking at [these lines](https://github.com/nadoo/glider/blob/master/proxy/mixed/mixed.go#L26-L50) you could just replace the Glider SOCKS5|HTTP proxy by the functions provided by the packages that this package uses.

What do you think @Snawoot?

**Comment by Snawoot** [comment]
@alpominth great idea, I like it!

Not sure if implementation will be that easy as copy-paste, though.

If someone will offer pull request with viable changeset, I'll be glad to accept it.

**Comment by alpominth** [comment]
@Snawoot 

Well, I do not know how to code in Go, but I asked ChatGPT for creating a sample program that listen on HTTP+SOCKS5: 

https://pastebin.com/tEcknUBx

Maybe, it could serve as a basis.

**Comment by CuteistFox** [comment]
remove the stale issue bot
