### ISSUE TITLE
"Opera Mini"'s proxies ?

### ISSUE THREAD

**Issue by GunGunGun** [Snawoot/opera-proxy#29]
Opera Mini has a very wide range of proxies and those are still unused by us, do you want to expand our list ?

APK: https://play.google.com/store/apps/details?id=com.opera.mini.native
Test IP: https://httpbin.org/ip
Test Headers: https://httpbin.org/headers

global-turbo2.opera-mini.net
global-turbo2-1.opera-mini.net
mini5.opera-mini.net
mini5-1.opera-mini.net

{ "headers": { "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9,image/webp", "Accept-Encoding": "gzip, deflate", "Accept-Language": "en-US,en;q=0.9", "Host": "httpbin.org", "Save-Data": "on", "Upgrade-Insecure-Requests": "1", "User-Agent": "Mozilla/5.0 (Linux; U; Android 5.1; A1601 Build/LMY47I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.74 Mobile Safari/537.36 OPR/66.1.2254.64111", "X-Amzn-Trace-Id": "Root=1-6386bfe8-197ce0d93c7bf32c59f3d7d0" } }

**Comment by Snawoot** [comment]
Hi! Unfortunately, I don't know API how to retrieve them and cant do reverse engineering of app right now. Do you know any details how to fetch these proxies?

**Comment by GunGunGun** [comment]
> Hi! Unfortunately, I don't know API how to retrieve them and cant do reverse engineering of app right now. Do you know any details how to fetch these proxies?

Hi Mr.Snawoot, many many years ago when Opera Mini was still the to-go browser for mobile device I successfully used Opera Mini proxy on Firefox and other browsers by changing HTTP header, but I believe they changed their API by a lot since then so I really don't know, I tried to sniff HTTP header and added Data-Save: 1 and they still rejected my request on http client API, I'll try to tamper Opera Mini's data on plain HTTP and see.
