### ISSUE TITLE
Windows versions

### ISSUE THREAD

**Issue by trimechee** [Snawoot/opera-proxy#30]
Hello, thank you for this awesome vpn ! 💯 🥇 

Please i have question, i see in releases page many windows versions , which version we should choose please ? i use windows 10 asus i3 : 

"opera-proxy.windows-386.exe or opera-proxy.windows-amd64.exe or opera-proxy.windows-arm.exe ?

**Comment by Snawoot** [comment]
Hi!

`amd64` for modern Intel/AMD 64bit CPUs, `386` for older 32bit Intel/AMD CPUs (this one may also run on 64bit CPU, though) and `arm` for ARM-based devices.

**Comment by trimechee** [comment]
My cpu is  Processeur Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz, 1992 MHz, 2 cœur(s), 4 processeur(s) logique(s), my notebook is asus year 2017, is it compatible with version amd64
or shoud i use version 386 ?

**Comment by Snawoot** [comment]
> My cpu is Processeur Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz, 1992 MHz, 2 cœur(s), 4 processeur(s) logique(s), my notebook is asus year 2017, is it compatible with version amd64 or shoud i use version 386 please ?

@trimechee You should use `amd64`.  Basically, you can just try: whatever is not compatible with your system will simply not run. But if `amd64` works for you, you should prefer it.
