### ISSUE TITLE
Feature suggestion: Idle timeout (keepalive)

### ISSUE THREAD

**Issue by przemyslaw0** [Snawoot/opera-proxy#35]
When using opera-proxy for things like DNS resolution with DoT or DoH, it could be faster if a keepalive connection is kept between client and server.

this feature is already implemented in a fork of opera-proxy: https://github.com/Snawoot/opera-proxy/commit/63f282b3bb569df58a757ed5b6d33c0783452649?diff=split

What do you think Snawoot?

**Comment by Snawoot** [comment]
Hi, @przemyslaw0 !

Changeset you mentioned is completely different thing. It's a time limit for the proxy to shutdown if there is no active connections. I see author of this fork also implemented the use of systemd socket activation. Whole thing is supposed to run opera-proxy only when it is really needed and terminate process when it's idle.

Regarding DoH and DoT, most likely it is already implemented from the client side. Usually DoH and DoT DNS stubs keep some pool of active connections with the DoH/DoT server and therefore keep underlying proxy connection active. If it's not the case for your client -- try other one, there are plenty around.
