### ISSUE TITLE
Change countries

### ISSUE THREAD

**Issue by trimechee** [Snawoot/opera-proxy#37]
Hello, I made several attempts before I could get Opera-Proxy to work, but I succeeded and I checked the IP address and I see that the location is in Europe, I read the description and the explanation on the Opera proxy github page and I tried but I did not succeed in changing the location of Opera-proxy to Asia or America, how to do it please ?

**Comment by Snawoot** [comment]
Hi! It should be easy. Just add `-country AS` or `-country AM` command line argument. If you're windows user, then create a shortcut to executable file and just add space and argument after executable file name. Some references how to do that:

https://www.digitalcitizen.life/shortcut-arguments-parameters-windows/
https://superuser.com/questions/29569/how-to-add-command-line-options-to-shortcut

**Comment by trimechee** [comment]
Awesome !! Thank you so great for your precious help @Snawoot  :) 💯 🥇
