### ISSUE TITLE
Multiplex between all proxies to increase throughput

### ISSUE THREAD

**Issue by grr** [Snawoot/opera-proxy#40]
To increase throughput, it would be nice if connections could be passed through all 3 proxies in turn. Although the user could run separate instances, one for each proxy available on a different port, that might only help if you have separate high-bandwidth apps and assign each to a different proxy. But if you have only a single high-bandwidth app, there's no way to use more than one proxy with a single app. At the app level or the OS level, I've only ever seen the option to use a single proxy. Maybe we need a separate proxy multiplexer program for this. This seems tangentially related: https://github.com/alexkirsz/dispatch

**Comment by Snawoot** [comment]
Hi! Different proxy endpoints would have different exit IP addresses, which may cause issues with visited sites. I don't think single server becomes the bottleneck which can be fixed with such load balancing, so for me it's hard to believe such use case will do any good.
