### ISSUE TITLE
No connections

### ISSUE THREAD

**Issue by trimechee** [Snawoot/opera-proxy#49]
Hello, Opera-proxy doesn't work any more, for exemple with : 

https://www.canalplus.com/c8/tpmp/touche-pas-a-mon-poste

I even try in combination with this extension to add a french ip address to the x forwarded for, but no connection, the Opera-proxy connection window displays no connection :

https://github.com/MisterPhilip/x-forwarded-for

before, I was able to watch videos from this French tv using Opera-proxy and x forwarded for ! but now impossible to watch videos from this tv channel !

**Comment by Snawoot** [comment]
Hello,

I just tried it and I can watch videos from the page you linked. Do you see any errors in opera-proxy log / console output?

**Comment by Snawoot** [comment]
> Ohh it's very surprising Mr @Snawoot that you can see the videos from this french tv channel because the videos are geoblocked !

I used opera-proxy. For my native IP or other proxy on hosted VM it shows "Access Denied", "IP", "REF", ...

> I tried with microsoft edge, firefox....web browsers and here a screenshot, apparently nothing happens....

Looks like your browser's traffic doesn't go through the proxy for some reason. There should be requests popping up in that terminal window. Maybe proxy is disabled in your systems settings? Or alternatively try following:

* Firefox has it's own proxy configuration available in preferences. Check it out.
* There is browser extensions like Proxy SwitchOmega which also do the trick and expose convenient button to switch between proxies and native connection.

**Comment by jestxfot** [comment]
@trimechee Try Omega Proxy

**Comment by trimechee** [comment]
Great ! Thank you so much Mr @jestxfot for you precious advise :) 🥇 💯 

it seems stable because  the last update was in 2018, and I found another effective and frequently updated proxy extension:

https://github.com/rNeomy/proxy-switcher/
