### ISSUE TITLE
How to use it with windows firewall block enabled?

### ISSUE THREAD

**Issue by vvkdev** [Snawoot/opera-proxy#50]
Hi!
I use windows 10 firewall with all default rules removed and with only my apps allowed.
If I run opera-proxy there no internet for it and I don't see any tries of it's exe that dropped by firewall.
How to give internet access to it?
Thank you.

**Comment by Snawoot** [comment]
hi! I have no idea. Maybe you should create allowing rule based on executable name?

**Comment by vvkdev** [comment]
Thank you for the reply! I found out that the service dnscache must be enabled for the app to work.

**Comment by alpominth** [comment]
@vvkdev vvkdev

I personally recommend this application for dealing with Windows firewall: https://www.sordum.org/8125/firewall-app-blocker-fab-v1-9/

You can add entire folders with hundreds of apps with some clicks.
