### ISSUE TITLE
 Unable to resolve api.sec-tunnel.com with specified bootstrap DNS

### ISSUE THREAD

**Issue by rootk1t** [Snawoot/opera-proxy#54]
Latest versions v1.3.0 & v1.3.1 show connection error:

D:\opera-proxy.windows-amd64.exe
MAIN    : 2024/07/06 20:41:25 main.go:129: INFO     opera-proxy client version v1.3.0 is starting...
MAIN    : 2024/07/06 20:41:25 main.go:165: INFO     Discovering API IP address...
MAIN    : 2024/07/06 20:41:26 main.go:168: CRITICAL Unable to resolve api.sec-tunnel.com with specified bootstrap DNS

nslookup api.sec-tunnel.com 8.8.8.8
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Server :     api.sec-tunnel.com
Addresses:  77.111.247.15
          77.111.247.17

v1.2.5 works:

D:\opera-proxy.windows-amd64.exe
MAIN    : 2024/07/06 20:45:50 main.go:129: INFO     opera-proxy client version v1.2.5 is starting...
MAIN    : 2024/07/06 20:45:51 main.go:284: INFO     Endpoint: 77.xxx.xx.xx:443
MAIN    : 2024/07/06 20:45:51 main.go:285: INFO     Starting proxy server...
MAIN    : 2024/07/06 20:45:51 main.go:287: INFO     Init complete.

**Comment by Snawoot** [comment]
Hello!

It seems https://1.1.1.3 is not available in your location. Following workarounds are possible:
* As you mentioned, just use v1.2.5.
* Turn off bootstrap DNS resolving at all with option `-bootstrap-dns=` (empty string value). System DNS will be used in that case.
* Use other DNS for bootstrap with `-bootstrap-dns=8.8.8.8` (plain DNS) or `-bootstrap-dns=https://8.8.8.8/dns-query` (DNS over HTTPS).
