### ISSUE TITLE
Need binary files platform details 

### ISSUE THREAD

**Issue by harshalgithub** [Snawoot/opera-proxy#55]
Hi @Snawoot   ,  can you please add descriptions to all prebuilt binary files and execution steps and platforms supported for all files please. 

Thanks.

**Comment by Snawoot** [comment]
Hello,

Binary file names have following format: `opera-proxy.${GOOS}-${GOARCH}`, where GOOS is codename of operating system and GOARCH, well, CPU architecture name. Worth noting that for Mac OS corresponding GOOS value is `darwin`.

Usually application is built with latest stable version of Go, so latest minimum requirements apply: https://go.dev/wiki/MinimumRequirements

Everything else is not related to particular release and will not appear on releases page. Consult your OS manual to learn how to run binary files on your platform.
