### ISSUE TITLE
Android or Google Smart TV installation

### ISSUE THREAD

**Issue by harshalgithub** [Snawoot/opera-proxy#60]
Hi Team,

How do we install this proxy into Android smart TV or Google TV 

Are the *.android.* files supported for installation?

Do we need to append ".apk" to the repository file for installation and what is minimum version of Android OS is supported ? Like Android 4 , Android 5?

Thank you

**Comment by Snawoot** [comment]
Hello!

Android files on releases page are not APK packages, those are just single binaries. You can run them with Termux or any other terminal emulator for Android.

Minimum Android version is Android 5.

**Comment by Snawoot** [comment]
> can we do that ?

@beshoo In theory it's possible, so go on and try.
