### ISSUE TITLE
The new version opera-proxy.windows-386 in my windows 7 os 32 bits doesn't work 

### ISSUE THREAD

**Issue by trimechee** [Snawoot/opera-proxy#64]
Hello, thank you so much for the new awesome version ! 💯

The release of August 2023 works perfectly in my windows 7 32 bits, , and I just installed the new last version v1.4.2 which unfortunately does not work on my asus eee pc windows 7 os 32 bits, a window appears briefly then closes when I click on :

opera-proxy.windows-386.exe

**Comment by Snawoot** [comment]
Hi!

Recent versions of golang do not support Windows 7. Try this unofficial patch to workaround this: https://github.com/stunndard/golangwin7patch
