### ISSUE TITLE
Add a local socks5 proxy.

### ISSUE THREAD

**Issue by paolosezart** [Snawoot/opera-proxy#68]
Is it difficult to add a local socks5 proxy? Or is it connected with some technical problems? I do not believe that the developers of such a wonderful, cross-platform program are not able to make it possible to connect to opera-proxy via socks protocol.
What is the problem or difficulty in realizing such a feature?

**Comment by Snawoot** [comment]
Hi!

There is no problem. I don't need SOCKS5 proxy in this app and don't consider this feature to be valuable addition to list of features I need to maintain. However, if someone will send a decent pull request with patches implementing it I'll be glad to accept.

As mentioned in previous issues on this topic (#15, #26) you can use some sort of adapter like [GO simple tunnel](https://latest.gost.run/en/)

```
gost -L socks5://127.0.0.1:8888 -F http://127.0.0.1:18080
```

**Comment by paolosezart** [comment]
> ```
> gost -L socks5://127.0.0.1:8888 -F http://127.0.0.1:18080
> ```
That's what I'm asking, instead of using external tools, why can't this be implemented in the program itself?

**Comment by Snawoot** [comment]
I already provided the answer in my previous message. It can be implemented. I won't do it just because you need it.

**Comment by midnight-wonderer** [comment]
### Been there; done that.
Worth it? __no!__ feature-wise.

Here are the relevant changes:
https://github.com/Snawoot/opera-proxy/compare/master...midnight-wonderer:feature/socks-listener?expand=1

Compile: `go build`  
Usage: `./opera-proxy -bind-address localhost:18081 -socks-mode`

@Snawoot, if you are interested in pulling in the changes, I can open a pull request for you.

### This is why it is usable for me:
I want to use it for my e-mail clients for some privacy, but Opera seems to restrict some outgoing ports. (587 included)  
So, I have no plans to use this for now.  
I am sure they restricted more ports; you could try with `gost` for your use cases before trying to build my branch.

**Comment by Snawoot** [comment]
@midnight-wonderer Sure, go for it. Gonna need some mention of the new option in README and then good to merge.
