### ISSUE TITLE
How to properly use the exported proxies?

### ISSUE THREAD

**Issue by savandriy** [Snawoot/opera-proxy#7]
Hi!

I wanted to use the opera proxies for a python project.

So, I downloaded the exe for windows, and did `opera-proxy.windows-amd64.exe -country EU -list-proxies`.
Everything worked as expected, I got the proxy list and the credentials.

But when trying to use the proxies in python, I would get:
`Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))`.

When trying to use the hostname instead of the proxy ip, I get this:
`Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11105990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))` - probably can't resolve the ip for the hostname.

I also thought that maybe those are secure web proxies, but it still failed:
`Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '77.111.244.65'. (_ssl.c:1056)")))`

Is there something specific about connecting to the opera proxies?

**Comment by Snawoot** [comment]
Hi!

Yes, there is a special trait of these proxies. They have no DNS name bound to them. But they still have TLS and you've got to validate TLS session certificate against specific DNS name provided along with proxy IP address.

You either have to use IP address as address of proxy host and override TLS handshake with expected cert hostname option OR use domain name as proxy host and override IP address where proxy client connects to.

curl example:

```
user@dt1:~> opera-proxy -list-proxies
MAIN    : 2021/05/12 16:25:53 main.go:129: INFO     opera-proxy client version v1.2.2 is starting...
Proxy login: 53980EC387AA6C18ECFB8C914F6ABDC6219A0E34
Proxy password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0RmVYWDdrV2FlMV9NUzhVUkZLZVFOM2t3R3Q3UUJxTGJYaEJEZ1Uwbmk4IiwieSI6IkpMN3JaaDJ5d0hKMV96eXBRVnlUM19BVUtnRk1BM3phendKbXRsTk9lY28ifX0.OQs-AfWQmExDqjo-2mQIqn8AzhZqthyyf2nof6gxOlaWjMar-aih7g.dJ6NOJVifA45-PVN.USdRV7JWko-Tz2GSitjCARjdrk5KRip4ss3G-CAYCV3iQGowIcyEePyK1rQ2Vu5etDRFswjl7P6iQwOlx0XGSS53_TY13QAwsrO4LDjvPmuswq9XUoOnGafxbWJXzlDp5F7N3wze47JwdfcjPxJ0GxqcRHfSSWU63TSzyHmbKOMH1eV4FnlZP_cvCviDca6JH8SPu7VEse4Rx7bpRoNKfEqmvI_dJ6K4WA7qT6biNM5csn9JUDE0lEocPvTQDSy2j4x_Ko_jHSi4ojnspj_EH3yVNSrHTwCeaHggkuVXzUoxWymbAkA6H5w5KDsfvmZFDrPuWNA4ytmoZxeah_lDj08ieSQ6-CO9BEFGY0I-iT-O1gPg5vkqxtOAQO4.Ko12v12xWuBaquYYY8t-Rg
Proxy-Authorization: Basic NTM5ODBFQzM4N0FBNkMxOEVDRkI4QzkxNEY2QUJEQzYyMTlBMEUzNDpleUpoYkdjaU9pSkZRMFJJTFVWVEswRXlOVFpMVnlJc0ltTjBlU0k2SWtwWFZDSXNJbVZ1WXlJNklrRXlOVFpIUTAwaUxDSmxjR3NpT25zaWEzUjVJam9pUlVNaUxDSmpjbllpT2lKUUxUSTFOaUlzSW5naU9pSTBSbVZZV0RkclYyRmxNVjlOVXpoVlVrWkxaVkZPTTJ0M1IzUTNVVUp4VEdKWWFFSkVaMVV3Ym1rNElpd2llU0k2SWtwTU4zSmFhREo1ZDBoS01WOTZlWEJSVm5sVU0xOUJWVXRuUmsxQk0zcGhlbmRLYlhSc1RrOWxZMjhpZlgwLk9Rcy1BZldRbUV4RHFqby0ybVFJcW44QXpoWnF0aHl5ZjJub2Y2Z3hPbGFXak1hci1haWg3Zy5kSjZOT0pWaWZBNDUtUFZOLlVTZFJWN0pXa28tVHoyR1NpdGpDQVJqZHJrNUtSaXA0c3MzRy1DQVlDVjNpUUdvd0ljeUVlUHlLMXJRMlZ1NWV0RFJGc3dqbDdQNmlRd09seDBYR1NTNTNfVFkxM1FBd3NyTzRMRGp2UG11c3dxOVhVb09uR2FmeGJXSlh6bERwNUY3TjN3emU0N0p3ZGZjalB4SjBHeHFjUkhmU1NXVTYzVFN6eUhtYktPTUgxZVY0Rm5sWlBfY3ZDdmlEY2E2Skg4U1B1N1ZFc2U0Ung3YnBSb05LZkVxbXZJX2RKNks0V0E3cVQ2YmlOTTVjc245SlVERTBsRW9jUHZUUURTeTJqNHhfS29fakhTaTRvam5zcGpfRUgzeVZOU3JIVHdDZWFIZ2drdVZYelVveFd5bWJBa0E2SDV3NUtEc2Z2bVpGRHJQdVdOQTR5dG1vWnhlYWhfbERqMDhpZVNRNi1DTzlCRUZHWTBJLWlULU8xZ1BnNXZrcXh0T0FRTzQuS28xMnYxMnhXdUJhcXVZWVk4dC1SZw==

host,ip_address,port
eu0.sec-tunnel.com,77.111.247.61,443
eu1.sec-tunnel.com,77.111.244.27,443
eu2.sec-tunnel.com,77.111.244.50,443
eu3.sec-tunnel.com,77.111.247.63,443
user@dt1:~> curl --proxy 'https://53980EC387AA6C18ECFB8C914F6ABDC6219A0E34:eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiI0RmVYWDdrV2FlMV9NUzhVUkZLZVFOM2t3R3Q3UUJxTGJYaEJEZ1Uwbmk4IiwieSI6IkpMN3JaaDJ5d0hKMV96eXBRVnlUM19BVUtnRk1BM3phendKbXRsTk9lY28ifX0.OQs-AfWQmExDqjo-2mQIqn8AzhZqthyyf2nof6gxOlaWjMar-aih7g.dJ6NOJVifA45-PVN.USdRV7JWko-Tz2GSitjCARjdrk5KRip4ss3G-CAYCV3iQGowIcyEePyK1rQ2Vu5etDRFswjl7P6iQwOlx0XGSS53_TY13QAwsrO4LDjvPmuswq9XUoOnGafxbWJXzlDp5F7N3wze47JwdfcjPxJ0GxqcRHfSSWU63TSzyHmbKOMH1eV4FnlZP_cvCviDca6JH8SPu7VEse4Rx7bpRoNKfEqmvI_dJ6K4WA7qT6biNM5csn9JUDE0lEocPvTQDSy2j4x_Ko_jHSi4ojnspj_EH3yVNSrHTwCeaHggkuVXzUoxWymbAkA6H5w5KDsfvmZFDrPuWNA4ytmoZxeah_lDj08ieSQ6-CO9BEFGY0I-iT-O1gPg5vkqxtOAQO4.Ko12v12xWuBaquYYY8t-Rg@eu0.sec-tunnel.com' --resolve eu0.sec-tunnel.com:443:77.111.247.61 https://api.ipify.org ; echo
77.111.247.61

```

**Comment by chuanhhoang** [comment]
The proxies doesn't seem to work. I receive error code 407 when using curl, as in your example.
`./opera-proxy -country EU -list-proxies
MAIN    : 2021/08/09 03:39:30 main.go:129: INFO     opera-proxy client version v1.2.2 is starting...
Proxy login: 833A1BB8865EDD8753A3DEA69F790EF2C2A6E59B
Proxy password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItTFRlWVo3dUtTTkp5WjBoY3l6NmJ0b3VvZWFhb2RZcGI0R3haNGMzVGVJIiwieSI6ImpFb3JzYklWNDJDS0ozR0FDWXRERWI4eW83THhPR1RmcVZxRlNNSENlR0UifX0.CmlrkFWCUO9-Gd5FcebsbrXlQewq1WcKp21Xx7lwlyFwzf1ToX4_tA.Wu0vwkZkET3gmwxw.Fd3ERaa0-pvvHK4JdlDLuZFBDWpjw_8zalVjSTd953Bk8YaStshgdJ4FoN1VJoaacS-DNVon7N8WTIcHiLiLJl008DUObM_dCHUTUEqNf2i2O5OSJjuAWhl1rC0XSpGvYLQ7RGLsCPLbAoCXkF90tzegsZy_gTeoRz55Azp2JmIhcIypqoSo8a1lcDSZSbOq5LWhLfowIhP9MgE7v0BpnJCu320m1J1IkbXTVJj5jSi1eb1nFoDt1vWrnMB2vib3xCrPrPCbvTnMn4upkUIovYzPF71E348ckXGWYB35c5v-mzCn8p4-llWxtj6cMYC_tgJY7apBGQytsafQbm36deAOCIR0sd02yqzHz0JyOWk_V4wgtok94ifrjwwqnIvPVVRV_O-LSpqK32BGRqvhndrUltoGE6Oy_v8vWBxRwPTq_P6XSCogm7N19m6vszkdk-hyA9kasDe6S8g.pyLIA8f7kazBymuXti0gVA
Proxy-Authorization: Basic ODMzQTFCQjg4NjVFREQ4NzUzQTNERUE2OUY3OTBFRjJDMkE2RTU5QjpleUpoYkdjaU9pSkZRMFJJTFVWVEswRXlOVFpMVnlJc0ltTjBlU0k2SWtwWFZDSXNJbVZ1WXlJNklrRXlOVFpIUTAwaUxDSmxjR3NpT25zaWEzUjVJam9pUlVNaUxDSmpjbllpT2lKUUxUSTFOaUlzSW5naU9pSXRURlJsV1ZvM2RVdFRUa3A1V2pCb1kzbDZObUowYjNWdlpXRmhiMlJaY0dJMFIzaGFOR016VkdWSklpd2llU0k2SW1wRmIzSnpZa2xXTkRKRFMwb3pSMEZEV1hSRVJXSTRlVzgzVEhoUFIxUm1jVlp4UmxOTlNFTmxSMFVpZlgwLkNtbHJrRldDVU85LUdkNUZjZWJzYnJYbFFld3ExV2NLcDIxWHg3bHdseUZ3emYxVG9YNF90QS5XdTB2d2taa0VUM2dtd3h3LkZkM0VSYWEwLXB2dkhLNEpkbERMdVpGQkRXcGp3Xzh6YWxWalNUZDk1M0JrOFlhU3RzaGdkSjRGb04xVkpvYWFjUy1ETlZvbjdOOFdUSWNIaUxpTEpsMDA4RFVPYk1fZENIVVRVRXFOZjJpMk81T1NKanVBV2hsMXJDMFhTcEd2WUxRN1JHTHNDUExiQW9DWGtGOTB0emVnc1p5X2dUZW9SejU1QXpwMkptSWhjSXlwcW9TbzhhMWxjRFNaU2JPcTVMV2hMZm93SWhQOU1nRTd2MEJwbkpDdTMyMG0xSjFJa2JYVFZKajVqU2kxZWIxbkZvRHQxdldybk1CMnZpYjN4Q3JQclBDYnZUbk1uNHVwa1VJb3ZZelBGNzFFMzQ4Y2tYR1dZQjM1YzV2LW16Q244cDQtbGxXeHRqNmNNWUNfdGdKWTdhcEJHUXl0c2FmUWJtMzZkZUFPQ0lSMHNkMDJ5cXpIejBKeU9Xa19WNHdndG9rOTRpZnJqd3dxbkl2UFZWUlZfTy1MU3BxSzMyQkdScXZobmRyVWx0b0dFNk95X3Y4dldCeFJ3UFRxX1A2WFNDb2dtN04xOW02dnN6a2RrLWh5QTlrYXNEZTZTOGcucHlMSUE4ZjdrYXpCeW11WHRpMGdWQQ==`


 `curl --proxy 'https://833A1BB8865EDD8753A3DEA69F790EF2C2A6E59B:eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItTFRlWVo3dUtTTkp5WjBoY3l6NmJ0b3VvZWFhb2RZcGI0R3haNGMzVGVJIiwieSI6ImpFb3JzYklWNDJDS0ozR0FDWXRERWI4eW83THhPR1RmcVZxRlNNSENlR0UifX0.CmlrkFWCUO9-Gd5FcebsbrXlQewq1WcKp21Xx7lwlyFwzf1ToX4_tA.Wu0vwkZkET3gmwxw.Fd3ERaa0-pvvHK4JdlDLuZFBDWpjw_8zalVjSTd953Bk8YaStshgdJ4FoN1VJoaacS-DNVon7N8WTIcHiLiLJl008DUObM_dCHUTUEqNf2i2O5OSJjuAWhl1rC0XSpGvYLQ7RGLsCPLbAoCXkF90tzegsZy_gTeoRz55Azp2JmIhcIypqoSo8a1lcDSZSbOq5LWhLfowIhP9MgE7v0BpnJCu320m1J1IkbXTVJj5jSi1eb1nFoDt1vWrnMB2vib3xCrPrPCbvTnMn4upkUIovYzPF71E348ckXGWYB35c5v-mzCn8p4-llWxtj6cMYC_tgJY7apBGQytsafQbm36deAOCIR0sd02yqzHz0JyOWk_V4wgtok94ifrjwwqnIvPVVRV_O-LSpqK32BGRqvhndrUltoGE6Oy_v8vWBxRwPTq_P6XSCogm7N19m6vszkdk-hyA9kasDe6S8g.pyLIA8f7kazBymuXti0gVA@eu0.sec-tunnel.com' --resolve eu0.sec-tunnel.com:443:77.111.247.241 https://api.ipify.org`

**Comment by Snawoot** [comment]
@chuanhhoang 

```
[00:04:44] dt1:~> curl --proxy 'https://833A1BB8865EDD8753A3DEA69F790EF2C2A6E59B:eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiItTFRlWVo3dUtTTkp5WjBoY3l6NmJ0b3VvZWFhb2RZcGI0R3haNGMzVGVJIiwieSI6ImpFb3JzYklWNDJDS0ozR0FDWXRERWI4eW83THhPR1RmcVZxRlNNSENlR0UifX0.CmlrkFWCUO9-Gd5FcebsbrXlQewq1WcKp21Xx7lwlyFwzf1ToX4_tA.Wu0vwkZkET3gmwxw.Fd3ERaa0-pvvHK4JdlDLuZFBDWpjw_8zalVjSTd953Bk8YaStshgdJ4FoN1VJoaacS-DNVon7N8WTIcHiLiLJl008DUObM_dCHUTUEqNf2i2O5OSJjuAWhl1rC0XSpGvYLQ7RGLsCPLbAoCXkF90tzegsZy_gTeoRz55Azp2JmIhcIypqoSo8a1lcDSZSbOq5LWhLfowIhP9MgE7v0BpnJCu320m1J1IkbXTVJj5jSi1eb1nFoDt1vWrnMB2vib3xCrPrPCbvTnMn4upkUIovYzPF71E348ckXGWYB35c5v-mzCn8p4-llWxtj6cMYC_tgJY7apBGQytsafQbm36deAOCIR0sd02yqzHz0JyOWk_V4wgtok94ifrjwwqnIvPVVRV_O-LSpqK32BGRqvhndrUltoGE6Oy_v8vWBxRwPTq_P6XSCogm7N19m6vszkdk-hyA9kasDe6S8g.pyLIA8f7kazBymuXti0gVA@eu0.sec-tunnel.com' --resolve eu0.sec-tunnel.com:443:77.111.247.241 https://api.ipify.org
77.111.247.241
```

Your curl command worked for me. Apparently your IP address originating requests got banned.
