### ISSUE TITLE
tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Baltazar500** [Snawoot/opera-proxy#74]
Решил обновить на старом девайсе opera-proxy и нашла коса на камень.

```
MAIN    : 2024/11/14 02:27:49 main.go:411: INFO     Attempting action "anonymous registration", attempt #2...
MAIN    : 2024/11/14 02:27:51 main.go:417: WARNING  Action "anonymous registration" failed: Post "https://api2.sec-tunnel.com/v4/register_subscriber": dial failed on address lookup: requesting https://1.1.1.3:443/dns-query: Get "https://1.1.1.3:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AAAEAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://1.1.1.3:443/dns-query: Get "https://1.1.1.3:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AABwAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://8.8.8.8:443/dns-query: Get "https://8.8.8.8:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AAAEAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://8.8.8.8:443/dns-query: Get "https://8.8.8.8:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AABwAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://security.cloudflare-dns.com:443/dns-query: Get "https://security.cloudflare-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AAAEAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://security.cloudflare-dns.com:443/dns-query: Get "https://security.cloudflare-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AABwAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://dns.quad9.net:443/dns-query: Get "https://dns.quad9.net:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AAAEAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://dns.quad9.net:443/dns-query: Get "https://dns.quad9.net:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AABwAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://dns.adguard-dns.com:443/dns-query: Get "https://dns.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AAAEAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://dns.adguard-dns.com:443/dns-query: Get "https://dns.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AABwAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://wikimedia-dns.org:443/dns-query: Get "https://wikimedia-dns.org:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AABwAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://wikimedia-dns.org:443/dns-query: Get "https://wikimedia-dns.org:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AAAEAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://dns.google:443/dns-query: Get "https://dns.google:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AABwAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://dns.google:443/dns-query: Get "https://dns.google:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AAAEAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://doh.cleanbrowsing.org:443/doh/adult-filter/: Get "https://doh.cleanbrowsing.org:443/doh/adult-filter/?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AABwAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
requesting https://doh.cleanbrowsing.org:443/doh/adult-filter/: Get "https://doh.cleanbrowsing.org:443/doh/adult-filter/?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AAAEAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
MAIN    : 2024/11/14 02:27:51 main.go:408: WARNING  Retrying action "anonymous registration" in 5s...
MAIN    : 2024/11/14 02:27:56 main.go:411: INFO     Attempting action "anonymous registration", attempt #3...
MAIN    : 2024/11/14 02:27:58 main.go:417: WARNING  Action "anonymous registration" failed: Post "https://api2.sec-tunnel.com/v4/register_subscriber": dial failed on address lookup: requesting https://1.1.1.3:443/dns-query: Get "https://1.1.1.3:443/dns-query?dns=AAABAAABAAAAAAAABGFwaTIKc2VjLXR1bm5lbANjb20AAAEAAQ": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
DOH - костыль не прокатывает из-за ветхости сертификатов и процесс подключения закручивается в петлю. -cafile тут не помогает. Нужен фикс/костыль в самом прокси. При этом старая ревизия, где нет DOH (но воткнут dnscrypt), работает без заморочек. Аналогичные фиксы кмк нужны и для остальных прокси, если там что-то подобное в плане запросов юзается (пока не проверял).

**Comment by Snawoot** [comment]
Добрый день! Это Windows 7?

**Comment by Baltazar500** [comment]
>Добрый день! Это Windows 7?

Привет. Нет, это не win 7. Это старый armv7 смарт. Бинарь linux-arm

**Comment by Snawoot** [comment]
Список используемых DNS управляется [опцией](https://github.com/Snawoot/opera-proxy?tab=readme-ov-file#list-of-arguments) `-bootstrap-dns`. Можно задать пустой список `-bootstrap-dns=`, можно задать одни DNS-ы из DNSCrypt.

С сертами проблема системная, я не считаю что это должно быть исправлено в каком бы то ни было софте.

**Comment by Snawoot** [comment]
> имелась ввиду опция по типу curl'овской "insecure" (-k), когда игнорятся ошибки сертификатов.

Не, вот этого в впн-софте точно делать не стоит. Можно вшить свежий пакет сертификатов в приложение, но тогда будут недовольны те, кто на роутерах его использует -- им и так оно еле в память влезает.

**Comment by Baltazar500** [comment]
@Snawoot, фишка в том, что те сертефикаты на гаджете не сказать что древние. Я хоть и обновлял 4 года назад, но протухнуть они ещё не должны были. Параллельно я воткнул свежий билд оперы - прокси на другой смарт и там всё было пучком. Сертификаты были новее, но кое-что более радикально отличалось. Бинарь была opera-proxy.android-arm64. 

В итоге у меня мелькнула мысль: "а не чудит ли это бинарь "opera-proxy.linux-arm" ? Втыкание бинари "opera-proxy.linux-arm" на смарт с "рабочей" оперой - прокси подтвердили мои догадки - она точно так же начали наворачивать запросы по кругу. Походу бинарь ищет сертификаты не в тех местах, где "нужно" :
```
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/pki/tls/certs/ca-bundle.crt", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ssl/ca-bundle.pem", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/pki/tls/cacert.pem", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ssl/cert.pem", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ssl/certs", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/pki/tls/certs", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```
По идее у бинари opera-proxy.android-arm таких заморочек быть не должно, вот только шлёт она лесом меня (и уже давно, почему и юзается linux-arm)

```
-bash-4.4# $tools/bin/opera-proxy.android-arm-1.6.0 -bind-address 127.0.0.1:55331 -country EU
soinfo_relocate(linker.cpp:992): cannot locate symbol "sigfillset" referenced by "/data/tools/bin/opera-proxy.android-arm-1.6.0"...CANNOT LINK EXECUTABLE
```
Тут или фикс android-arm бинари нужен или возможность указания хранилища сертификатов (если затык в этом).

**Comment by Snawoot** [comment]
> По идее у бинари opera-proxy.android-arm таких заморочек быть не должно, вот только шлёт она лесом меня (и уже давно, почему и юзается linux-arm)
> 
> ```
> -bash-4.4# $tools/bin/opera-proxy.android-arm-1.6.0 -bind-address 127.0.0.1:55331 -country EU
> soinfo_relocate(linker.cpp:992): cannot locate symbol "sigfillset" referenced by "/data/tools/bin/opera-proxy.android-arm-1.6.0"...CANNOT LINK EXECUTABLE
> ```

А какая там версия андроида?

**Comment by Baltazar500** [comment]
>А какая там версия андроида?

4.2.2, по нынешним меркам древность, но для сёрфинга и ютуба (newpipe) этого на 90% хватает

**Comment by ZaWertun** [comment]
> Походу бинарь ищет сертификаты не в тех местах, где "нужно"

В бинарниках Go можно сделать оверрайд мест, где он ищет корневые сертификаты с помощью перменных окружения `SSL_CERT_FILE`, `SSL_CERT_DIR`.
(см. https://go.dev/src/crypto/x509/root_unix.go)

Может поможет.

**Comment by Snawoot** [comment]
> 4.2.2

Сборка бинарей на андроид идёт под API level 21, что соответствует 5.0 и выше. Можете попробовать так же пересобрать со старым NDK.

**Comment by Baltazar500** [comment]
@ZaWertun, 
>В бинарниках Go можно сделать оверрайд мест, где он ищет корневые сертификаты с помощью перменных окружения SSL_CERT_FILE, SSL_CERT_DIR.
(см. https://go.dev/src/crypto/x509/root_unix.go)

Это вы писали мне как пользователю или тому, кто будет собирать ? Со сборкой у меня всё грустно в принципе и скилл по этой линии не прокачан.

@Snawoot,
>Сборка бинарей на андроид идёт под API level 21, что соответствует 5.0 и выше. Можете попробовать так же пересобрать со старым NDK.

Из меня очень плохой сборщик. Особенно если происходит затык с зависимостями.

>У меня на старом ноуте нашёлся некий ndk-toolchain-arm/bin/armv7a-linux-androideabi19-clang и вроде бы удалось с ним собрать -- попробуйте: [opera-proxy.android-arm.zip](https://github.com/user-attachments/files/17751450/opera-proxy.android-arm.zip)

Завелось без каких-либо проблем. Спасибо.

**Comment by Snawoot** [comment]
> Из меня очень плохой сборщик. Особенно если происходит затык с зависимостями.

Ну поддерживать такие старые устройства на регулярной основе мне не хочется - это меньше 0.4% аудитории, а проблем с окружением добавит.

> p.s. А разве 4.2.2 это не api level 17 ? Просто бинари на api на 2 уровня выше вроде уже не должны заводиться. Или я чего-то не понимаю :) ?

Видимо повезло просто, что в итоговой сборке оказались задействованы только функции не старше 17. Прикладываю ещё собранный для 17го 
[opera-proxy.android-arm.zip](https://github.com/user-attachments/files/17772015/opera-proxy.android-arm.zip)

**Comment by Baltazar500** [comment]
>Ну поддерживать такие старые устройства на регулярной основе мне не хочется - это меньше 0.4% аудитории, а проблем с окружением добавит. Если вам хочется заниматься с такими старыми устройствами, то придётся овладеть таким умением.

Да у меня и с новыми туго :( ...

>Видимо повезло просто, что в итоговой сборке оказались задействованы только функции не старше 17. Прикладываю ещё собранный для 17го

Спасибо, проверю.

Чтобы далеко не отходить от темы, можете собрать hola-proxy ? Там те же яйца, вид сбоку

```
-bash-4.4# hola-proxy -bind-address 127.0.0.1:55123 -country de
MAIN    : 2024/11/15 09:38:51 main.go:193: INFO     hola-proxy client version v1.14.0 is starting...
MAIN    : 2024/11/15 09:38:51 main.go:261: INFO     Attempting action "get latest version of browser extension", attempt #1...
MAIN    : 2024/11/15 09:38:55 main.go:267: WARNING  Action "get latest version of browser extension" failed: chrome web store request failed: Get "https://clients2.google.com/service/update2/crx?acceptformat=crx2%2Ccrx3&prodversion=113.0&x=id%3Dgkojfkhlekighikafcpjkiklfbnlmeio%26uc%3D": tls: failed to verify certificate: x509: certificate signed by unknown authority
MAIN    : 2024/11/15 09:38:55 main.go:258: WARNING  Retrying action "get latest version of browser extension" in 5s...
MAIN    : 2024/11/15 09:39:01 main.go:261: INFO     Attempting action "get latest version of browser extension", attempt #2...
MAIN    : 2024/11/15 09:39:01 main.go:267: WARNING  Action "get latest version of browser extension" failed: chrome web store request failed: Get "https://clients2.google.com/service/update2/crx?acceptformat=crx2%2Ccrx3&prodversion=113.0&x=id%3Dgkojfkhlekighikafcpjkiklfbnlmeio%26uc%3D": tls: failed to verify certificate: x509: certificate signed by unknown authority
MAIN    : 2024/11/15 09:39:01 main.go:258: WARNING  Retrying action "get latest version of browser extension" in 5s...
MAIN    : 2024/11/15 09:39:06 main.go:261: INFO     Attempting action "get latest version of browser extension", attempt #3...
MAIN    : 2024/11/15 09:39:06 main.go:267: WARNING  Action "get latest version of browser extension" failed: chrome web store request failed: Get "https://clients2.google.com/service/update2/crx?acceptformat=crx2%2Ccrx3&prodversion=113.0&x=id%3Dgkojfkhlekighikafcpjkiklfbnlmeio%26uc%3D": tls: failed to verify certificate: x509: certificate signed by unknown authority
MAIN    : 2024/11/15 09:39:06 main.go:258: WARNING  Retrying action "get latest version of browser extension" in 5s...
MAIN    : 2024/11/15 09:39:11 main.go:261: INFO     Attempting action "get latest version of browser extension", attempt #4...
MAIN    : 2024/11/15 09:39:11 main.go:267: WARNING  Action "get latest version of browser extension" failed: chrome web store request failed: Get "https://clients2.google.com/service/update2/crx?acceptformat=crx2%2Ccrx3&prodversion=113.0&x=id%3Dgkojfkhlekighikafcpjkiklfbnlmeio%26uc%3D": tls: failed to verify certificate: x509: certificate signed by unknown authority
MAIN    : 2024/11/15 09:39:11 main.go:258: WARNING  Retrying action "get latest version of browser extension" in 5s...
MAIN    : 2024/11/15 09:39:16 main.go:261: INFO     Attempting action "get latest version of browser extension", attempt #5...
^C
```

**Comment by Baltazar500** [comment]
Сделал ;)
