### ISSUE TITLE
Is it possible to change IP

### ISSUE THREAD

**Issue by masksshow** [Snawoot/opera-proxy#8]
Hello, great project!!!
I noticed that every time I start, I get a different IP for the duration of the entire project launch.
Is it possible to change IP, for example by time or external command call? We need rotation.

**Comment by Snawoot** [comment]
Hello! Thanks!

Such feature is not implemented. I think [hola-proxy](https://github.com/Snawoot/hola-proxy) will suit your needs better because it has larger choice of countries and servers. Both hola-proxy and opera-proxy have `-list-proxies` option which allows to export list of proxies and credentials to rotate them as you need. However, direct use of proxies exported by opera-proxy is tricky: #7 That's another reason to use hola-proxy for your purpose.

**Comment by cturan** [comment]
I want to share my own method for Rotate proxy with python 3

It does not cause any problems up to about 500,000 requests per day.

`import os
import time

import requests
import itertools

requests.packages.urllib3.disable_warnings()

def run_exe(exe_path):
    username = ""
    password = ""
    p = os.popen(exe_path)
    time.sleep(5)
    for line in p:
        if "Proxy login:" in line:
            username = line.split(":")[1].strip()
        if "Proxy password:" in line:
            password = line.split(":")[1].strip()
    p.close()
    if username == "" or password == "":
        return False
    return username, password


proxy_data = run_exe("proxy.exe -country EU -list-proxies")
if not proxy_data:
    print("Proxy Error")
    exit()
proxy_username, proxy_password = proxy_data

# All location opera proxy ip list.
proxy_list = ["77.111.245.10:443", "77.111.245.11:443", "77.111.245.12:443", "77.111.245.13:443", "77.111.245.14:443",
              "77.111.246.4:443", "77.111.246.5:443", "77.111.246.6:443", "77.111.246.8:443", "77.111.246.9:443",
              "77.111.246.10:443", "77.111.246.13:443", "77.111.246.14:443", "77.111.246.15:443", "77.111.246.21:443",
              "77.111.246.22:443", "77.111.246.23:443", "77.111.246.31:443", "77.111.246.40:443", "77.111.246.41:443",
              "77.111.246.42:443", "77.111.246.43:443", "77.111.246.44:443", "77.111.246.45:443", "77.111.246.46:443",
              "77.111.246.47:443", "77.111.246.48:443", "77.111.246.49:443", "77.111.246.126:443", "77.111.247.4:443",
              "77.111.247.5:443", "77.111.247.6:443", "77.111.247.7:443", "77.111.247.8:443", "77.111.247.9:443",
              "77.111.247.10:443", "77.111.247.11:443", "77.111.247.12:443", "77.111.247.13:443", "77.111.247.21:443",
              "77.111.247.22:443", "77.111.247.30:443", "77.111.247.31:443", "77.111.247.41:443", "77.111.247.43:443",
              "77.111.247.44:443", "77.111.247.45:443", "77.111.247.46:443", "77.111.247.47:443", "77.111.247.48:443",
              "77.111.247.49:443", "77.111.247.50:443", "77.111.247.54:443", "77.111.247.55:443", "77.111.247.56:443",
              "77.111.247.57:443", "77.111.247.58:443", "77.111.247.59:443", "77.111.247.60:443", "77.111.247.61:443",
              "77.111.247.62:443", "77.111.247.64:443", "77.111.247.65:443", "77.111.247.66:443", "77.111.247.67:443",
              "77.111.247.68:443", "77.111.247.69:443", "77.111.247.71:443", "77.111.247.72:443", "77.111.247.73:443",
              "77.111.247.74:443", "77.111.247.75:443", "77.111.247.76:443", "77.111.247.77:443", "77.111.247.81:443",
              "77.111.247.82:443", "77.111.247.90:443", "77.111.247.91:443", "77.111.247.99:443", "77.111.247.100:443",
              "77.111.247.108:443", "77.111.247.109:443", "77.111.247.117:443", "77.111.247.119:443",
              "77.111.247.120:443", "77.111.247.128:443", "77.111.247.129:443", "77.111.247.137:443",
              "77.111.247.138:443", "77.111.247.146:443", "77.111.247.147:443", "77.111.247.159:443",
              "77.111.247.160:443", "77.111.247.168:443", "77.111.247.169:443", "77.111.247.182:443",
              "77.111.247.183:443", "77.111.247.184:443", "77.111.247.186:443", "77.111.247.187:443",
              "77.111.247.205:443", "77.111.247.206:443", "77.111.247.214:443", "77.111.247.215:443",
              "77.111.247.223:443", "77.111.247.224:443", "77.111.247.232:443", "77.111.247.233:443",
              "77.111.247.250:443", "77.111.247.251:443", "77.111.247.252:443", "77.111.247.253:443"]

proxy_list_cycle = itertools.cycle(proxy_list)

for i in range(1, 10):
    selected_proxy = {
        "https": "https://" + proxy_username + ":" + proxy_password + "@" + next(proxy_list_cycle),
        "http": "https://" + proxy_username + ":" + proxy_password + "@" + next(proxy_list_cycle)
    }
    response = requests.get("https://api.ipify.org/?format=json", proxies=selected_proxy, verify=False)
    print(response.text)
`
