### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by GGPay** [Snawoot/opera-proxy#9]
Got an error while building container

Log below

`
Building opera-proxy
Step 1/17 : FROM golang AS build
 ---> 1b8b0ceece59
Step 2/17 : ARG GIT_DESC=undefined
 ---> Using cache
 ---> 2405fc5bf4ec
Step 3/17 : WORKDIR /go/src/github.com/Snawoot/opera-proxy
 ---> Running in 8dda67de6a20
Removing intermediate container 8dda67de6a20
 ---> f521b30c36bf
Step 4/17 : COPY . .
 ---> 2bfd4c278f65
Step 5/17 : RUN CGO_ENABLED=0 go build -a -tags netgo -ldflags '-s -w -extldflags "-static" -X main.version='"$GIT_DESC"
 ---> Running in 7667f03d75a8
go: downloading github.com/AdguardTeam/dnsproxy v0.36.0
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/Snawoot/go-http-digest-auth-client v1.1.3
go: downloading golang.org/x/net v0.0.0-20210324205630-d1beb07c2056
go: downloading github.com/joomcode/errorx v1.0.3
go: downloading github.com/lucas-clemente/quic-go v0.19.3
go: downloading github.com/AdguardTeam/golibs v0.4.4
go: downloading github.com/ameshkov/dnscrypt/v2 v2.0.1
go: downloading github.com/ameshkov/dnsstamps v1.0.3
go: downloading golang.org/x/crypto v0.0.0-20201208171446-5f87f3452ae9
go: downloading golang.org/x/sys v0.0.0-20210324051608-47abb6519492
go: downloading github.com/cheekybits/genny v1.0.0
go: downloading golang.org/x/text v0.3.4
go: downloading github.com/marten-seemann/qtls-go1-15 v0.1.1
go: downloading github.com/aead/chacha20 v0.0.0-20180709150244-8b13a72661da
go: downloading github.com/aead/poly1305 v0.0.0-20180717145839-3fee0db0b635
'# github.com/Snawoot/go-http-digest-auth-client
/go/pkg/mod/github.com/!snawoot/go-http-digest-auth-client@v1.1.3/authorization.go:109:15: undefined: io.NopCloser
/go/pkg/mod/github.com/!snawoot/go-http-digest-auth-client@v1.1.3/digest_auth_client.go:49:18: undefined: io.NopCloser
/go/pkg/mod/github.com/!snawoot/go-http-digest-auth-client@v1.1.3/digest_auth_client.go:59:21: undefined: io.NopCloser
note: module requires Go 1.16
ERROR: Service 'opera-proxy' failed to build: The command '/bin/sh -c CGO_ENABLED=0 go build -a -tags netgo -ldflags '-s -w -extldflags "-static" -X main.version='"$GIT_DESC"' returned a non-zero code: 2

`

**Comment by Snawoot** [comment]
Hi!

It seems you're trying to build it with older golang base image. Required golang version is 1.16. In order to update your golang base image you can issue command `docker pull golang`.

**Comment by GGPay** [comment]
Thank you so much! That's right - updating golang solve the issue.
